[package]
name = "gh-keys"
version = "0.1.0"
authors = ["Don Petersen <don@donpetersen.net>"]

[dependencies]
hyper = "0.4.0"
rustc-serialize = "0.3"
log = "0.3"
fern = "0.3"
time = "0.1"
getopts = "0.2"
